version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/aws-cicd-test
    overwrite: yes

permissions:
  - object: /home/ubuntu/aws-cicd-test/
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60